# Generated by Django 5.0.4 on 2024-08-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('data_lancamento', models.DateField()),
            ],
        ),
    ]
